[log]
level = "debug"

[kafka.config]
"group.id" = "elara-api"
"bootstrap.servers" = "localhost:9092"
"enable.partition.eof" = "false"
"session.timeout.ms" = "6000"
"enable.auto.commit" = "true"

[kafka]
topics = ["polkadot", "kusama"]

[ws]
addr = "localhost:9002"